# allow: SIZE_OK — single-pipeline codegen module (AST collect → C++ emit);
# ~1/3 of LOC is verbatim C++ template strings (data, not logic). Splitting
# would scatter one pipeline across files for no reviewer gain.
"""
serializer_gen.py — Per-struct trace serializer codegen with heap identity.

Generates C++ serializers for user-defined structs found in the AST::

    {"$id": int, "$addr": "0x...", <field>: <value>, ...}

Identity scheme (see docs/serializer-design.md):
- ``$id`` is an int, stable per address within one program run via a
  void\\*-keyed global map (``__heap_ids``). Two vars pointing at the same
  address share one ``$id`` (aliasing).
- ``$addr`` is emitted ALONGSIDE ``$id`` (additive — ``$addr``-only
  consumers keep working; parser/frontend untouched).
- Pointers: ``null`` when null; ``{"$ref": id, "$cycle": true}`` on
  visited-set re-entry (terminates cycles); ``{"$ref": id}`` on repeat
  sighting within one call; full object on first sighting.
- Every STATE re-emits full fields with the same ``$id`` (no cross-event
  ``$ref``-collapse), so single-field mutations diff to one field (R6).
- Containers: explicit ``__ser`` specializations for
  ``std::vector<T>`` / ``std::vector<T*>`` per struct T emit
  ``{"$id", "$addr", "items"}``. All other container shapes are untouched.
- Field names are cross-checked against the AST; on ANY mismatch the
  struct is skipped. Zero structs → ``{"structs": []}`` manifest and a
  comment-only C++ stub (existing ``$addr`` fallback behavior unchanged).

Carve-outs: unions, bitfields, anonymous fields, and template
instantiations are skipped (never fabricated). Lookup relies on ADL —
user structs live in the global namespace, so dependent ``__ser`` calls
inside tracer.h templates find the generated overloads; the injector
appends this output at end-of-file (struct types complete there).
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field

import clang.cindex as clang

from app.core.instrumenter import _libclang_compat

logger = logging.getLogger(__name__)

_lib = _libclang_compat.ensure_libclang()

_FIELD_NAME_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")

_RUNTIME = """\
// ---- struct serializer runtime (generated by serializer_gen.py) ----
inline std::unordered_map<void*, int> __heap_ids;
inline int __heap_next_id = 1;
inline int __heap_id_for(const void* p) {
    auto it = __heap_ids.find(const_cast<void*>(p));
    if (it != __heap_ids.end()) return it->second;
    int id = __heap_next_id++;
    __heap_ids[const_cast<void*>(p)] = id;
    return id;
}
inline std::string __heap_ref(int id, bool cycle) {
    std::ostringstream o;
    o << "{\\"$ref\\":" << id;
    if (cycle) o << ",\\"$cycle\\":true";
    return o.str() + "}";
}
"""


@dataclass
class FieldDef:
    """One emittable struct field."""

    name: str
    # "default" → __ser(obj.f); "struct_ptr" → recurse via pointee's
    # serializer (null → null); "struct_value" → recurse on the member.
    kind: str = "default"
    target: str = ""  # struct name for struct_ptr / struct_value


@dataclass
class StructDef:
    name: str
    fields: list[FieldDef] = field(default_factory=list)


def _is_user_code(cursor: clang.Cursor, source_path: str) -> bool:
    loc = cursor.location
    return loc.file is not None and os.path.abspath(loc.file.name) == os.path.abspath(source_path)


def _normalize_type(spelling: str) -> str:
    s = spelling.strip()
    for prefix in ("const ", "volatile ", "struct ", "class ", "enum "):
        while s.startswith(prefix):
            s = s[len(prefix) :]
    s = s.rstrip("&").rstrip("*").strip()
    for prefix in ("const ", "volatile "):
        while s.startswith(prefix):
            s = s[len(prefix) :]
    return s.strip()


def _short_name(spelling: str) -> str:
    return spelling.split("::")[-1].strip()


def collect_structs(source_path: str) -> list[StructDef]:
    """Collect emittable user-defined structs from *source_path*.

    Never raises: any parse problem yields ``[]`` (graceful fallback).
    Skips: non-user code, unions, templates, structs with anonymous /
    bitfield / union-typed fields, structs with unresolvable fields.
    """
    try:
        index = clang.Index.create()
        tu = index.parse(source_path, args=["-std=c++17", "-O0"])
    except (clang.TranslationUnitLoadError, RuntimeError, ValueError, OSError):
        return []
    try:
        return _collect_from_tu(tu, source_path)
    except (AttributeError, TypeError, RuntimeError, ValueError):
        return []


def _collect_from_tu(tu: object, source_path: str) -> list[StructDef]:
    records: list[clang.Cursor] = []

    def visit(cursor: clang.Cursor) -> None:
        try:
            if cursor.kind == clang.CursorKind.UNION_DECL:
                return  # carve-out: never descend into unions
            if (
                cursor.kind
                in (
                    clang.CursorKind.STRUCT_DECL,
                    clang.CursorKind.CLASS_DECL,
                )
                and cursor.is_definition()
            ):
                try:
                    if _is_user_code(cursor, source_path) and cursor.spelling:
                        records.append(cursor)
                except (AttributeError, TypeError, RuntimeError, ValueError):
                    logger.debug("skipping struct cursor", exc_info=True)
            for child in cursor.get_children():
                visit(child)
        except (AttributeError, TypeError, RuntimeError, ValueError):
            return

    visit(tu.cursor)

    names = {c.spelling for c in records}
    out: list[StructDef] = []
    for cursor in records:
        try:
            struct_def = _struct_def(cursor, names, source_path)
        except (AttributeError, TypeError, RuntimeError, ValueError):
            logger.debug("skipping unresolvable struct", exc_info=True)
            continue
        if struct_def is not None:
            out.append(struct_def)
    return out


def _struct_def(cursor: clang.Cursor, names: set[str], source_path: str) -> StructDef | None:
    if not cursor.spelling or not _FIELD_NAME_RE.match(cursor.spelling):
        return None
    fields: list[FieldDef] = []
    for child in cursor.get_children():
        if child.kind != clang.CursorKind.FIELD_DECL:
            continue
        if not child.spelling or not _FIELD_NAME_RE.match(child.spelling):
            return None  # anonymous field → skip whole struct
        try:
            if child.is_bitfield():
                return None  # carve-out: cannot take address
        except (AttributeError, TypeError, RuntimeError, ValueError):
            return None
        try:
            kind, target = _classify_field(child, names)
        except (AttributeError, TypeError, RuntimeError, ValueError):
            return None
        fields.append(FieldDef(name=child.spelling, kind=kind, target=target))
    return StructDef(name=cursor.spelling, fields=fields)


def _classify_field(field_cursor: clang.Cursor, names: set[str]) -> tuple[str, str]:
    """Return (kind, target-struct-name) for a FIELD_DECL."""
    try:
        canon = field_cursor.type.get_canonical()
    except (AttributeError, TypeError, RuntimeError, ValueError):
        raise ValueError("unresolvable type")
    # Union-typed field → skip whole struct (active-member ambiguity).
    try:
        decl = canon.get_declaration()
        if decl is not None and decl.kind == clang.CursorKind.UNION_DECL:
            raise ValueError("union field")
    except ValueError:
        raise
    except (AttributeError, TypeError, RuntimeError):
        pass
    try:
        if canon.kind == clang.TypeKind.POINTER:
            pointee = _normalize_type(canon.get_pointee().get_canonical().spelling)
            match = _match_struct(pointee, names)
            if match is not None:
                return ("struct_ptr", match)
            return ("default", "")
        if canon.kind in (
            clang.TypeKind.LVALUEREFERENCE,
            clang.TypeKind.RVALUEREFERENCE,
        ):
            pointee = _normalize_type(canon.get_pointee().get_canonical().spelling)
            match = _match_struct(pointee, names)
            if match is not None:
                return ("struct_value", match)
            return ("default", "")
        norm = _normalize_type(canon.spelling)
        match = _match_struct(norm, names)
        if match is not None:
            return ("struct_value", match)
        return ("default", "")
    except ValueError:
        raise
    except (AttributeError, TypeError, RuntimeError):
        raise ValueError("unclassifiable field")


def _match_struct(normalized: str, names: set[str]) -> str | None:
    if normalized in names:
        return normalized
    short = _short_name(normalized)
    for name in names:
        if name == short or _short_name(name) == short:
            return name
    return None


def manifest(source_path: str) -> dict:
    """Return ``{"structs": [names...]}`` for *source_path*."""
    return {"structs": [s.name for s in collect_structs(source_path)]}


def generate_serializers(source_path: str) -> str:
    """Generate the C++ serializer block for *source_path*.

    Never raises: on any failure returns a comment-only stub so the
    existing ``$addr`` fallback path is unchanged.
    """
    try:
        structs = collect_structs(source_path)
    except (AttributeError, TypeError, RuntimeError, ValueError, OSError):
        structs = []
    if not structs:
        return '// serializer_gen: no emittable structs (manifest {"structs": []})\n'
    try:
        parts = [_RUNTIME]
        parts.append(
            "\n".join(
                f"inline std::string __serialize_{s.name}(const {s.name}& obj, "
                "std::set<void*>& visited, std::set<void*>& emitted, int depth);"
                for s in structs
            )
            + "\n"
        )
        for s in structs:
            parts.append(_emit_struct(s))
        for s in structs:
            parts.append(_emit_overloads(s))
            parts.append(_emit_vector_specs(s))
        return "\n".join(parts)
    except (AttributeError, TypeError, RuntimeError, ValueError):
        return "// serializer_gen: codegen failed; falling back to $addr behavior\n"


def _emit_struct(s: StructDef) -> str:
    lines = [
        (
            f"inline std::string __serialize_{s.name}(const {s.name}& obj, "
            "std::set<void*>& visited, std::set<void*>& emitted, int depth) {"
        ),
        '    if (depth > 50) return "{\\"$depth_limit\\":true}";',
        "    void* addr = (void*)&obj;",
        "    int id = __heap_id_for(addr);",
        '    if (__trace_freed_addresses.count(addr)) return "{\\"$ref\\":" + std::to_string(id) + ",\\"$freed\\":true}";',
        "    if (visited.count(addr)) return __heap_ref(id, true);",
        "    if (emitted.count(addr)) return __heap_ref(id, false);",
        "    visited.insert(addr);",
        "    std::ostringstream o;",
        '    o << "{\\"$id\\":" << id << ",\\"$addr\\":\\"" << addr << "\\"";',
    ]
    for f in s.fields:
        if f.kind == "struct_ptr":
            lines.append(
                f'    o << ",\\"{f.name}\\":";'
                f'if (!obj.{f.name}) o << "null"; '
                f"else o << __serialize_{f.target}"
                f"(*obj.{f.name}, visited, emitted, depth + 1);"
            )
        elif f.kind == "struct_value":
            lines.append(
                f'    o << ",\\"{f.name}\\":" '
                f"<< __serialize_{f.target}"
                f"(obj.{f.name}, visited, emitted, depth + 1);"
            )
        else:
            lines.append(f'    o << ",\\"{f.name}\\":" << __ser(obj.{f.name});')
    lines += [
        '    o << "}";',
        "    visited.erase(addr);",
        "    emitted.insert(addr);",
        "    return o.str();",
        "}",
    ]
    return "\n".join(lines) + "\n"


def _emit_overloads(s: StructDef) -> str:
    return f"""\
inline std::string __ser(const {s.name}& obj) {{
    std::set<void*> visited, emitted;
    return __serialize_{s.name}(obj, visited, emitted, 0);
}}
inline std::string __ser({s.name}* p) {{
    if (!p) return "null";
    std::set<void*> visited, emitted;
    return __serialize_{s.name}(*p, visited, emitted, 0);
}}
inline std::string __ser(const {s.name}* p) {{
    if (!p) return "null";
    std::set<void*> visited, emitted;
    return __serialize_{s.name}(*p, visited, emitted, 0);
}}
"""


def _emit_vector_specs(s: StructDef) -> str:
    by_value = f"""\
template<>
inline std::string __ser(const std::vector<{s.name}>& v) {{
    int id = __heap_id_for((const void*)&v);
    std::set<void*> visited, emitted;
    std::ostringstream o;
    o << "{{\\"$id\\":" << id << ",\\"$addr\\":\\"" << (const void*)&v << "\\",\\"items\\":[";
    for (size_t i = 0; i < v.size(); ++i) {{
        if (i) o << ",";
        o << __serialize_{s.name}(v[i], visited, emitted, 0);
    }}
    o << "]}}";
    return o.str();
}}
"""
    by_ptr = f"""\
template<>
inline std::string __ser(const std::vector<{s.name}*>& v) {{
    int id = __heap_id_for((const void*)&v);
    std::set<void*> visited, emitted;
    std::ostringstream o;
    o << "{{\\"$id\\":" << id << ",\\"$addr\\":\\"" << (const void*)&v << "\\",\\"items\\":[";
    for (size_t i = 0; i < v.size(); ++i) {{
        if (i) o << ",";
        if (!v[i]) o << "null";
        else o << __serialize_{s.name}(*v[i], visited, emitted, 0);
    }}
    o << "]}}";
    return o.str();
}}
"""
    return by_value + "\n" + by_ptr
