/**
 * tests/scale-slo.spec.ts — Todo 26 H4 scale SLO benchmark trio (R7.1/R7.2/R7.6).
 *
 * Legs (NDJSON fixtures generated by bench/scale.bench.ts into
 * bench/fixtures/<leg>.ndjson, route-mocked as **\/execute):
 *   nested-loop   ~10k steps   (100x100 loop, vars {i,j})
 *   fib-recursion ~50k steps   (fib(21) call tree, enter/state/exit per call)
 *   hot-call      ~100k steps  (25k iters x state/enter/state/exit)
 *
 * Per leg (headless Chromium, real dev server on :3001, CI=1):
 *   - load wall-time through the REAL streaming path (appendEvent per line),
 *     capped by LEG_TIMEOUT_MS -> "timeout" verdict, never a hang.
 *   - scrub-step p95 via performance.now around slider-driven setStep,
 *     3 repeats -> median-of-medians (flaky-timing probe).
 *   - collapsed DOM count via querySelectorAll("*").
 *   - payload bytes from the fixture file on disk.
 *   - browser spot reachability (first/last/spread steps via the slider).
 * Full 100% raw-step reachability (expand-then-step every raw index) runs in
 * bench/scale.bench.ts against the real traceStore; this spec asserts on
 * measured numbers written to bench/scale-browser.json, never console echoes.
 */

import { test, expect } from "@playwright/test";
import * as fs from "node:fs";
import * as path from "node:path";

const BENCH_DIR = path.join(import.meta.dirname, "..", "bench");
const FIX_DIR = path.join(BENCH_DIR, "fixtures");
const OUT_PATH = path.join(BENCH_DIR, "scale-browser.json");
const BASELINE_PATH = path.join(BENCH_DIR, "vector-baseline.json");

const LEGS = ["nested-loop", "fib-recursion", "hot-call"] as const;
type LegId = (typeof LEGS)[number];

const LEG_TIMEOUT_MS = 300_000; // per-leg wall-time cap (probe a: never hang)
const SAMPLES = 21; // scrub samples per repeat
const REPEATS = 3; // flaky-timing probe: 3x repeat, median-of-medians

interface LegResult {
  total_steps: number;
  payload_bytes: number;
  load_ms: number;
  verdict: "measured" | "timeout";
  p95_ms: number | null;
  repeat_p95s: number[];
  dom_collapsed: number | null;
  spot_reach_pct: number | null;
}

function readTotalSteps(ndjson: string): number {
  let total = 0;
  for (const line of ndjson.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    const chunk = JSON.parse(t) as { type: string; total_steps?: number };
    if (chunk.type === "cfg") total = chunk.total_steps ?? total;
  }
  return total;
}

/** Drive the scrubber slider to `step`; returns performance.now() delta. */
async function nav(
  page: import("@playwright/test").Page,
  step: number,
): Promise<number> {
  const t0 = await page.evaluate(() => performance.now());
  await page.evaluate((s) => {
    const el = document.querySelector<HTMLInputElement>(
      'input[aria-label="Trace step"]',
    )!;
    const setter = Object.getOwnPropertyDescriptor(
      HTMLInputElement.prototype,
      "value",
    )!.set!;
    setter.call(el, String(s));
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }, step);
  await page.waitForFunction(
    (s) => {
      const el = document.querySelector<HTMLInputElement>(
        'input[aria-label="Trace step"]',
      );
      return el !== null && Number(el.value) === s;
    },
    step,
    { timeout: 30_000 },
  );
  const t1 = await page.evaluate(() => performance.now());
  return t1 - t0;
}

function p95(xs: number[]): number {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(0.95 * s.length) - 1)];
}

function median(xs: number[]): number {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
}

function spreadSteps(total: number, n: number): number[] {
  const out: number[] = [];
  for (let k = 0; k < n; k++) {
    out.push(Math.min(total - 1, Math.floor(((k + 0.5) * total) / n)));
  }
  return out;
}

async function measureLeg(
  page: import("@playwright/test").Page,
  leg: LegId,
  t0load: number,
): Promise<LegResult> {
  const fixPath = path.join(FIX_DIR, `${leg}.ndjson`);
  // Missing fixture file => honest RED, not a silent skip.
  expect(
    fs.existsSync(fixPath),
    `fixture missing: ${fixPath} (run bench/scale.bench.ts fixtures first)`,
  ).toBe(true);
  const ndjson = fs.readFileSync(fixPath, "utf8");
  const payload_bytes = fs.statSync(fixPath).size;
  const total = readTotalSteps(ndjson);
  expect(total, `${leg}: cfg.total_steps must be > 0`).toBeGreaterThan(0);

  await page.route("**/execute", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/x-ndjson",
      body: ndjson,
    }),
  );
  await page.goto("/");
  await page.getByRole("button", { name: /^Run$/ }).click();
  await page.waitForSelector('input[aria-label="Trace step"]', {
    timeout: LEG_TIMEOUT_MS,
  });
  const load_ms = Date.now() - t0load;

  // Collapsed DOM count (nothing expanded by default).
  const dom_collapsed = await page.evaluate(
    () => document.querySelectorAll("*").length,
  );

  // Spot reachability: first / last / spread steps land exactly.
  const spots = [0, total - 1, ...spreadSteps(total, 8)];
  let ok = 0;
  for (const s of spots) {
    await nav(page, s);
    const v = await page.evaluate(
      () =>
        Number(
          document.querySelector<HTMLInputElement>(
            'input[aria-label="Trace step"]',
          )!.value,
        ),
    );
    if (v === s) ok++;
  }

  // 3x repeat of the p95 leg (probe b); report median-of-medians.
  const repeat_p95s: number[] = [];
  for (let r = 0; r < REPEATS; r++) {
    const samples: number[] = [];
    for (const s of spreadSteps(total, SAMPLES)) samples.push(await nav(page, s));
    repeat_p95s.push(p95(samples));
  }

  return {
    total_steps: total,
    payload_bytes,
    load_ms,
    verdict: "measured",
    p95_ms: median(repeat_p95s),
    repeat_p95s,
    dom_collapsed,
    spot_reach_pct: (100 * ok) / spots.length,
  };
}

test.describe("scale SLO trio", () => {
  test("all legs: load, p95 scrub, collapsed DOM, spot reachability", async ({
    page,
    browser,
  }) => {
    test.setTimeout(1_200_000);
    const t0 = Date.now();
    const legs: Record<string, LegResult> = {};
    for (const leg of LEGS) {
      const t0load = Date.now();
      try {
        legs[leg] = await measureLeg(page, leg, t0load);
      } catch (e) {
        // Timeout verdict (probe a): record, never hang; fail honestly below.
        legs[leg] = {
          total_steps: -1,
          payload_bytes: fs.existsSync(path.join(FIX_DIR, `${leg}.ndjson`))
            ? fs.statSync(path.join(FIX_DIR, `${leg}.ndjson`)).size
            : -1,
          load_ms: Date.now() - t0load,
          verdict: "timeout",
          p95_ms: null,
          repeat_p95s: [],
          dom_collapsed: null,
          spot_reach_pct: null,
        };
        throw e;
      } finally {
        await page.unroute("**/execute");
      }
    }

    const browserVersion = browser.version();
    const report = {
      measured_at: new Date().toISOString(),
      browser: "chromium",
      browser_version: browserVersion,
      wall_total_ms: Date.now() - t0,
      legs,
    };
    fs.mkdirSync(BENCH_DIR, { recursive: true });
    fs.writeFileSync(OUT_PATH, JSON.stringify(report, null, 2) + "\n");

    // Assert on measured numbers (probe c): p95 gate evaluated in the
    // bench runner for the final verdict; here assert data completeness.
    for (const leg of LEGS) {
      expect(legs[leg].verdict).toBe("measured");
      expect(legs[leg].p95_ms).not.toBeNull();
      expect(legs[leg].spot_reach_pct).toBe(100);
    }
  });

  test("vector-flash guard vs baseline (R7.6)", async ({ page }) => {
    test.setTimeout(300_000);
    const v1 = Array.from({ length: 1000 }, (_, i) => i);
    const v2 = [...v1];
    v2[500] = -1;
    const ev = [
      { type: "enter", line: 1, func: "main", depth: 1, params: {} },
      { type: "state", line: 2, func: "main", depth: 1, vars: { arr: v1 } },
      { type: "state", line: 3, func: "main", depth: 1, vars: { arr: v2 } },
      { type: "exit", line: 4, func: "main", depth: 1, return_val: 0 },
    ];
    const lines = ev.map((e) => JSON.stringify({ type: "event", data: e }));
    lines.push(
      JSON.stringify({
        type: "cfg",
        stdout: "",
        runtime_error: null,
        timed_out: false,
        truncated: false,
        cfg_nodes: [
          { id: "n0", type: "func_start", lines: [1], label: "main()", children: ["n1"], trace_indices: [0] },
          { id: "n1", type: "line", lines: [2, 3], label: "body", children: ["n2"], trace_indices: [1, 2] },
          { id: "n2", type: "func_end", lines: [4], label: "return", children: [], trace_indices: [3] },
        ],
        cfg_edges: [
          { source: "n0", target: "n1", label: "" },
          { source: "n1", target: "n2", label: "" },
        ],
        total_steps: 4,
      }),
    );
    await page.route("**/execute", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/x-ndjson",
        body: lines.join("\n") + "\n",
      }),
    );
    await page.goto("/");
    await page.getByRole("button", { name: /^Run$/ }).click();
    await page.waitForSelector('input[aria-label="Trace step"]', {
      timeout: 60_000,
    });
    await page.waitForTimeout(500);
    const samples: number[] = [];
    for (let i = 0; i < 15; i++) {
      samples.push(await nav(page, 2));
      samples.push(await nav(page, 1));
    }
    const med = median(samples);
    const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, "utf8")) as {
      median_ms: number;
    };
    const ratio = med / baseline.median_ms;
    console.log(
      `VECTOR_GUARD median=${med.toFixed(2)}ms baseline=${baseline.median_ms.toFixed(2)}ms ratio=${ratio.toFixed(3)}`,
    );
    const prev = fs.existsSync(OUT_PATH)
      ? JSON.parse(fs.readFileSync(OUT_PATH, "utf8") as string)
      : {};
    fs.writeFileSync(
      OUT_PATH,
      JSON.stringify(
        { ...prev, vector_guard: { median_ms: med, baseline_ms: baseline.median_ms, ratio, pass: ratio <= 1.2 } },
        null,
        2,
      ) + "\n",
    );
    expect(ratio, `vector-flash regression: ratio ${ratio.toFixed(3)} > 1.2`).toBeLessThanOrEqual(1.2);
  });
});
